---
# tasks file for netatalk-ansible

- name: Load Platform Specific Variables
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}.yml"

- name: Install OS Family packages required for compilation
  apt: pkg={{ item }} state=latest cache_valid_time=3600 update_cache=yes
  with_items: os_family_packages
  tags:
    - install_requirements

- name: Display netatalk version being installed
  debug: var=netatalk_version

- name: Download Netatalk tarball
  get_url: url=http://prdownloads.sourceforge.net/netatalk/{{ netatalk_version }}.tar.gz?download dest=/tmp/{{ netatalk_version }}.tar.gz
  tags:
    - tarball_installation

- name: Extract tarball
  command: /bin/tar xf /tmp/{{ netatalk_version }}.tar.gz -C {{ source_location }} creates={{ source_location }}/{{ netatalk_version }}
  tags:
    - tarball_installation

- name: Generate Makefile ( ./configure )
  command: >
    chdir={{ source_location }}/{{ netatalk_version }}
    creates=Makefile
    ./configure
        --with-init-style=debian-sysv
        --without-libevent
        --without-tdb
        --with-cracklib
        --enable-krbV-uam
        --with-pam-confdir=/etc/pam.d
        --with-dbus-sysconf-dir=/etc/dbus-1/system.d
        --with-tracker-pkgconfig-version=1.0
  register: config
  tags:
    - tarball_installation

- name: ( ./configure ) output
  debug: var=config.stdout_lines
  tags:
    - tarball_installation

- name: Compile Netatalk for source ( make )
  command: make chdir={{ source_location }}/{{ netatalk_version }}
  register: make
  tags:
    - tarball_installation

# - name: ( make ) output
#   debug: var=make.stdout_lines
#   tags:
#     - tarball_installation

- name: Install Netatalk Binaries ( make install )
  command: make install chdir={{ source_location }}/{{ netatalk_version }}
  register: make_install
  tags:
    - tarball_installation

# - name: (make install) output
#   debug: var=make_install.stdout_lines
#   tags:
#     - tarball_installation


- name: Configure AFP Shares
  template: src=templates/usr_local_src_etc_afp.conf.j2 dest=/usr/local/etc/afp.conf backup=yes
  notify:
    - restart netatalk
  tags:
    - configure_services

- name: Configure Avahi Service
  template: src=templates/etc_avahi_services_afpd.service.j2 dest=/etc/avahi/services/afpd.service backup=yes owner=avahi group=root mode=0774
  notify:
    - restart avahi
  tags:
    - configure_services

- name: Verify existance of afp share folders
  file: path={{ item.path }} state=directory owner=root
  with_items: shares_list
  when: shares_list is defined
  tags:
    - create_folders

- name: Verify existance of Time Machine Volume and set permissions accordingly
  file: path={{ tm_volume.path }} state=directory owner=root mode=774
  tags:
    - create_folders

- name: Enable Netatalk Service
  service: name=netatalk state=started enabled=yes pattern=/usr/local/sbin/netatalk
  tags:
    - start_services

- name: Enable Avahi Service
  service: name=avahi-daemon state=started enabled=yes
  tags:
    - start_services